# Generated by Django 6.0.4 on 2026-04-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_user_updated_at_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('store', 'Store'), ('manager', 'Manager'), ('superadmin', 'Super Admin')], max_length=20),
        ),
    ]
