# Generated by Django 6.0.4 on 2026-04-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Current stock quantity available'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='reorder_level',
            field=models.IntegerField(default=10, help_text='Alert when stock goes below this level'),
        ),
    ]
